CREATE TABLE UNIT
(
	ID INT NOT NULL PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL
)

CREATE TABLE FOOD (
  ID INT NOT NULL PRIMARY KEY,
  CALORIES INT NOT NULL,
  FAT INT NOT NULL,
  CARBOHYDRATE INT NOT NULL,
  FIBER INT NOT NULL,
  PROTEIN INT NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PORTION_AMOUNT INT NOT NULL,
  PORTION_UNIT INT NOT NULL,
  FOREIGN KEY(PORTION_UNIT) REFERENCES UNIT(ID)
);
